version: "3"
services:
  app:
    restart: always
    build: ./app
    # uncomment for development
    # volumes:
    #   - ./app:/usr/src/app/
    ports:
      - "9000:9000"

  database:
    image: mongo_with_seed_data
    build: ./mongo
    volumes:
      - ./data:/data/db

