version: "3"
services:
  app:
    restart: always
    build: ./app
    # uncomment for development
    # volumes:
    #   - ./app:/usr/src/app/
    ports:
      - "9000:9000"

  database:
    image: mongo:3.6.5
    volumes:
      - ./data:/data/db

  mongo_seed:
    image: mongo_seed
    build: ./mongo
