version: "3.5"
services:
  app:
    restart: always
    build: ./app
    # uncomment for development
    # volumes:
    #   - ./app:/usr/src/app/
    ports:
      - "9000:9000"
    networks:
      - backend

  database:
    image: mongo_database
    build: ./mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge
