version: "2"
services:
  app:
    container_name: app
    restart: always
    build: ./app
    # uncomment for development 
    # volumes:
    #   - ./app:/usr/src/app/
    ports:
      - "9000:9000"
    links:
      - database

  database:
    container_name: database
    image: mongo:3.0.2
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  mongo_seed:
    image: mongo_seed
    build: ./mongo
    links:
      - database
